import os
import numpy as np
import pandas as pd

configfile: "config/config.yaml"

# Global paths
TMP_ROOT = os.path.join(os.path.expanduser("~/scratch"))
SUPPORT_DIR = "support"

# global variables
ALPHAGENOME_FOLDS = config["variables"]["ALPHAGENOME_FOLDS"]

# Save params for pandas to_csv
SAVE_PARAMS = {"sep": "\t", "index": False, "compression": "gzip"}

include: "rules/data/gencode.smk"
include: "rules/data/sf3b1mut.smk"
include: "rules/data/hepg2.smk"

include: "rules/data/alphagenome.smk"
include: "rules/models/alphagenome.smk"

#include: "rules/data/borzoi.smk"
#include: "rules/models/borzoi.smk"

rule all:
    input:
        # data
        ## download and preprocess reference genome
        config["gencode"]["paths"]["fasta"],
        config["gencode"]["paths"]["gtf"],
        config["gencode"]["paths"]["gtf_parquet"],
        config["gencode"]["paths"]["star_index"],

        ## HepG2 ENCODE FASTQs
        # expand(
        #     os.path.join(config["rnaseq"]["hepg2"]["path"], "fastqs", ".done", "{sample}_{end}"),
        #     sample=list(SAMPLES_HEPG2.keys()),
        #     end=ENDS_HEPG2,
        # ),

        ## download raw reads, align, preprocess for finetuning
        os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "bigwig_mapping-with_mapped_reads.tsv.gz"),
        os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "merged.second_pass.ReadsPerGene.out.tab.gz"),
        expand(
           os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "{sample}", "second_pass.ssu.parquet"),
           sample=SAMPLES,
           strand=["fwd", "rev"],
        ),

        ## paper-settings alignment (single-pass, outSAMstrandField intronMotif)
        # expand(
        #    os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "{sample}", "paper_pass.SJ.{strand}.tab"),
        #    sample=SAMPLES,
        #    strand=["fwd", "rev"],
        # ),

        # ## AlphaGenome finetuning (one done file per fold)
        # expand(
        #     os.path.join(config["finetuning"]["alphagenome"]["sf3b1mut"]["output_dir"], "{fold}", ".done"),
        #     fold=ALPHAGENOME_FOLDS,
        # ),

        # ## Borzoi finetuning (one done file per replicate)
        # expand(
        #     os.path.join(config["finetuning"]["borzoi"]["sf3b1mut"]["output_dir"], "rep{rep}", ".done"),
        #     rep=range(config["borzoi"]["num_reps"]),
        # ),
