import os
import numpy as np
import pandas as pd

configfile: "config/config.yaml"

# Global paths
TMP_ROOT = os.path.join(os.path.expanduser("~/scratch"))
SUPPORT_DIR = "support"

# Global variables
ALPHAGENOME_FOLDS = config["variables"]["ALPHAGENOME_FOLDS"]

# Save params for pandas to_csv
SAVE_PARAMS = {"sep": "\t", "index": False, "compression": "gzip"}

include: "rules/gencode.smk"
include: "rules/sf3b1mut.smk"
include: "rules/alphagenome.smk"
include: "rules/comparison_ssu.smk"

rule all:
    input:
        # GENCODE reference genome and annotation
        config["gencode"]["paths"]["fasta"],
        config["gencode"]["paths"]["gtf"],
        config["gencode"]["paths"]["gtf_parquet"],
        config["gencode"]["paths"]["star_index"],

        # SF3B1 RNA-seq: bigwigs, gene expression, splice site usage
        os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "bigwig_mapping-with_mapped_reads.tsv.gz"),
        os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "merged.second_pass.ReadsPerGene.out.tab.gz"),
        expand(
            os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "{sample}", "paper_pass.ssu.parquet"),
            sample=SAMPLES,
        ),

        # AlphaGenome model weights and fold interval BED files
        config["alphagenome_pytorch"]["paths"]["weights"],
        config["finetuning"]["alphagenome"]["sequences_bed_gz"],
        expand(
            os.path.join(config["finetuning"]["alphagenome"]["folds_dir"], "{fold}", "{split}.bed"),
            fold=ALPHAGENOME_FOLDS,
            split=["train", "valid", "test"],
        ),

        # SSU comparison: custom compute_ssu vs SpliSER, with resource benchmarks
        expand(
            os.path.join(SSU_OUTPUT_DIR, "custom", "{sample}", "paper_pass.ssu.parquet"),
            sample=SSU_BENCHMARK_SAMPLES,
        ),
        expand(
            os.path.join(SSU_OUTPUT_DIR, "spliser", "{sample}", "{sample}.SpliSER.tsv"),
            sample=SSU_BENCHMARK_SAMPLES,
        ),
        os.path.join(SSU_OUTPUT_DIR, "benchmarks", "benchmarks.parquet"),
