import os
import numpy as np
import pandas as pd

configfile: "config/config.yaml"

# Global paths
TMP_ROOT = os.path.join(os.path.expanduser("~/scratch"))
SUPPORT_DIR = "support"
SCRIPTS_DIR = "src/scripts"

# Global variables
ALPHAGENOME_FOLDS = config["variables"]["ALPHAGENOME_FOLDS"]

# Save params for pandas to_csv
SAVE_PARAMS = {"sep": "\t", "index": False, "compression": "gzip"}

include: "rules/gencode.smk"
include: "rules/sf3b1mut.smk"
include: "rules/alphagenome.smk"
include: "rules/comparison_ssu.smk"
include: "rules/alphagenome_jax.smk"
include: "rules/k562.smk"

rule all:
    input:
        # GENCODE reference genome and annotation
        config["gencode"]["paths"]["fasta"],
        config["gencode"]["paths"]["gtf"],
        config["gencode"]["paths"]["gtf_parquet"],
        config["gencode"]["paths"]["star_index"],

        # SF3B1 RNA-seq: bigwigs, gene expression, splice site usage
        os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "bigwig_mapping-with_mapped_reads.tsv.gz"),
        os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "merged.second_pass.ReadsPerGene.out.tab.gz"),
        expand(
            os.path.join(config["rnaseq"]["sf3b1mut"]["path"], "STAR", "{sample}", "paper_pass.ssu.parquet"),
            sample=SAMPLES,
        ),

        # AlphaGenome model weights and fold interval BED files
        config["alphagenome_pytorch"]["paths"]["weights"],
        config["finetuning"]["alphagenome"]["sequences_bed_gz"],
        expand(
            os.path.join(config["finetuning"]["alphagenome"]["folds_dir"], "{fold}", "{split}.bed"),
            fold=ALPHAGENOME_FOLDS,
            split=["train", "valid", "test"],
        ),

        # SSU comparison: custom compute_ssu vs SpliSER, with resource benchmarks
        expand(
            os.path.join(SSU_OUTPUT_DIR, "junctions", "{sample}.starlike.SJ.out.tab"),
            sample=SSU_BENCHMARK_SAMPLES,
        ),
        expand(
            os.path.join(SSU_OUTPUT_DIR, "custom", "{sample}", "paper_pass.ssu.parquet"),
            sample=SSU_BENCHMARK_SAMPLES,
        ),
        expand(
            os.path.join(SSU_OUTPUT_DIR, "spliser", "{sample}", "{sample}.SpliSER.tsv"),
            sample=SSU_BENCHMARK_SAMPLES,
        ),
        os.path.join(SSU_OUTPUT_DIR, "benchmarks", "benchmarks.parquet"),

        # AlphaGenome JAX pretraining TFRecords + extracted K562 SSU parquets
        expand(
            os.path.join(config["alphagenome_jax"]["path"], "{fold_split}", "{organism}", "{subset}", "{bundle}", ".done"),
            fold_split=ALPHAGENOME_JAX_FOLD_SPLITS,
            organism=ALPHAGENOME_JAX_ORGANISMS,
            subset=ALPHAGENOME_JAX_SUBSETS,
            bundle=ALPHAGENOME_JAX_BUNDLES,
        ),
        expand(
            os.path.join(config["alphagenome_jax"]["path"], "{fold_split}", "{organism}", "{subset}", "k562_ssu.parquet"),
            fold_split=ALPHAGENOME_JAX_FOLD_SPLITS,
            organism=ALPHAGENOME_JAX_ORGANISMS,
            subset=ALPHAGENOME_JAX_SUBSETS,
        ),
        os.path.join(config["alphagenome_jax"]["path"], "k562_ssu_merged.parquet"),

        # K562 ENCODE RNA-seq: bigwigs and splice site usage
        expand(
            os.path.join(config["rnaseq"]["k562"]["path"], "STAR", "{sample}", "paper_pass.ssu.parquet"),
            sample=K562_SAMPLES,
        ),
        expand(
            os.path.join(config["rnaseq"]["k562"]["path"], "STAR", ".done_make_bw", "{sample}-{strand}"),
            sample=K562_SAMPLES,
            strand=K562_STRANDS,
        ),
